name: Build & Push BIRD2

on:
  workflow_dispatch:

jobs:
  push:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    strategy:
      fail-fast: true
      matrix:
        arch:
          - "amd64"
        image:
          - "bird"
    steps:
      - uses: actions/checkout@v4

      - name: Set Versions
        id: set_ver
        run: |
          echo IMAGE_VER=`jq .image_version ${{matrix.image}}/versions.json` >> $GITHUB_OUTPUT
          echo ALPINE_VER=`jq .alpine_version ${{matrix.image}}/versions.json` >> $GITHUB_OUTPUT
          echo BUSYBOX_ENV=`jq .busybox_version ${{matrix.image}}/versions.json` >> $GITHUB_OUTPUT
          echo COMMIT_TS=`TZ=UTC git show -s --format=%cd --date=format-local:'%y%m%d%H%M'` >> $GITHUB_OUTPUT

      - name: Build image
        run: |
          cd ${{matrix.image}}
          docker build --file Dockerfile --tag ${{matrix.image}} --label "runnumber=${GITHUB_RUN_ID}"

      - name: Log in to registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
        #
      - name: Push image
        run: |
          IMAGE_ID=ghcr.io/${{ github.repository_owner }}/${{matrix.image}}

          # This changes all uppercase characters to lowercase.
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
          echo IMAGE_ID=$IMAGE_ID
          echo VERSION=${{steps.outputs.set_ver.IMAGE_VER}}-${{steps.outputs.set_ver.COMMIT_TS}}
          docker tag ${{matrix.image}} $IMAGE_ID:$VERSION
          docker push $IMAGE_ID:$VERSION

